### ISSUE TITLE
No results output when running RSpec

### ISSUE THREAD

**Issue by Drenmi** [nevir/Bumbler#15]
Hi, there!

I was hoping to use Bumbler to profile the (currently very slow) boot up of our RSpec test suite. Unfortunately, Bumbler doesn't output the results after the loading finished. It displays the progress bar correctly, i.e.:

```
$ bundle exec rspec
[#########                                                                     ]
( 7/59)  492.04ms loaded pry
```

However, after the loading finished, the test suite starts, and no Bumbler results are ever printed.

**Comment by willsu** [comment]
In my case, I am unable to see the progress bar for the Rails env when I run an RSpec command. I am using the following command:

```
RUBYOPT='rbumbler/go' bundle exec rspec spec/foo/bar/baz_spec.rb
```

Note: I had to remove the `-` character in order to go the `go.rb` file to load correctly.

I am running `rbenv 0.4.0` and `ruby 2.2.3p173`

**Comment by grosser** [comment]
inside the tests you still have to trigger the printing of the slow gems with `Bumbler::Stats.print_slow_items`
