### ISSUE TITLE
Ruby broken.  Cannot load such file -- bumble/go (LoadError)

### ISSUE THREAD

**Issue by matt-burgess** [nevir/Bumbler#16]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bumbler/go (LoadError)

I've tried numerous things to get past this error.  Has anyone dealt with this and was able to get past it?

**Comment by moggyboy** [comment]
I just uninstalled the gem, removed the command from my .zshrc (or .bashrc or whatever you used) and restarted the terminal after having that problem, and it went away.

**Comment by matt-burgess** [comment]
The only solution I've found is executing `export export RUBYOPT=` in Terminal every time my computer restarts.  Do you know how to permanently change this?  I'm not familiar with .shrc or .bashrc or the others that I might have setup initially.

**Comment by etcook** [comment]
@matt-burgess The other option is to run 'export RUBYOPT=-rbumbler/go' manually instead of putting it in your shell profile.
