### ISSUE TITLE
Mysterious :finisher_hook in results?

### ISSUE THREAD

**Issue by xanview** [nevir/Bumbler#17]
I am seeing the following in my Rails 5.1.2 app:

```
$ bumbler --initializers
Slow requires:
    212.38  :set_routes_reloader_hook
    315.04  ./config/initializers/mac_address_db.rb
    650.10  ./config/initializers/preview_interceptors.rb
   2203.82  ./config/initializers/messaging.rb
   3208.06  :load_config_initializers
  110146.25  :finisher_hook
```

Any ideas what is this weird :finisher_hook that is taking up the majority of the load time?

**Comment by grosser** [comment]
nope, dig up rails source and see what it does

**Comment by xanview** [comment]
No idea, but seems it was unrelated to what was causing the problem, I had this in config/initializers/sidekiq.rb: "Sidekiq::Extensions.enable_delay!" -- once I commented this line out, the load time went down from 90 to 5 seconds.

So it seems bumbler --initializers couldn't pick up the sidekiq.rb initializer file for some reason?

**Comment by grosser** [comment]
maybe because it's triggered later somehow ... or it's bugged ... try
poking around in the gem to find out more :)

**Comment by grosser** [comment]
let me know if you can still reproduce ... I rewrote a lot so this might be fixed by accident
