### ISSUE TITLE
Make it work for any Bundler-based projects?

### ISSUE THREAD

**Issue by janko** [nevir/Bumbler#18]
The description of the gem says that it works for any "Bundler-based" projects, but when I tried to run it inside the root directory of one of my gems, I get an error:

```
LoadError: cannot load such file -- ./config/environment
  /Users/janko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bumbler-0.3.2/lib/bumbler/hooks.rb:35:in `require'
  /Users/janko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bumbler-0.3.2/lib/bumbler/hooks.rb:35:in `call'
  /Users/janko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bumbler-0.3.2/lib/bumbler/hooks.rb:35:in `block (3 levels) in hook_require!'
  /Users/janko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bumbler-0.3.2/lib/bumbler/hooks.rb:68:in `handle_require'
  /Users/janko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bumbler-0.3.2/lib/bumbler/hooks.rb:34:in `block (2 levels) in hook_require!'
  /Users/janko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bumbler-0.3.2/bin/bumbler:37:in `<top (required)>'
  /Users/janko/.rbenv/versions/2.4.1/bin/bumbler:22:in `load'
  /Users/janko/.rbenv/versions/2.4.1/bin/bumbler:22:in `<top (required)>'
```

Would it be possible to make it work for any Bundler-based project, not just Rails? Btw, I'm really impressed with the gem, my friend executed it on one of his Rails projects and the information was super useful (I care about load time).

**Comment by grosser** [comment]
how can it work inside a gem ? ... require the first file it finds in lib/
and then measure load times ?
... could run it with an extra argument to give it an entrypoint to load ...

**Comment by janko-m** [comment]
Hmm, I wasn't aware that an entrypoint file is needed, I thought it uses Bundler to retrieve a list of gems specified in the `Gemfile`, and makes its own requires. I guess if it needs to have an entrypoint in the project that will require all the gems, then an extra argument specifying the file to load sounds like a good idea.

**Comment by grosser** [comment]
done
