### ISSUE TITLE
Gems with require: true are ignored

### ISSUE THREAD

**Issue by pelargir** [nevir/Bumbler#21]
If a Gemfile specifies `require: true` for a given gem, that gem is ignored by Bumbler.

Specifying `require: true` may seem redundant, but it is supported syntax per the Bundler documentation and can be a useful callout:
https://bundler.io/man/gemfile.5.html

The reason this is happening can be found in `bundler.rb` on line 43:

```
Array(spec.autorequire || spec.name).each do |path|
  @require_map[path] = spec.name
  @gem_state[spec.name][path] = false
end
```

When `require: true` is set in the Gemfile, the result of `spec.autorequire` is also `true` which gets inserted into the `@require_map` as the path key (instead of an actual path). This causes `#gem_for_require` to return nil for that gem.

This bug can be reliably reproduced by running Bumbler, noting one of the slow gems listed, and modifying the `Gemfile` with `require: true` for this gem. Run Bumbler again and you won't see the gem appear anywhere in the list of slow gems.

**Comment by grosser** [comment]
sounds reasonable, can you make a PR ?

**Comment by pelargir** [comment]
@grosser done, although I'm open to suggestions for a cleaner way to do this.
