### ISSUE TITLE
Bumbler stops at half of the gems

### ISSUE THREAD

**Issue by 23tux** [nevir/Bumbler#23]
Running on Ruby 2.6.3, bumbler stops when about half the gems are loaded. You can see this here, that the progress bar is not filled:

```
root@7d8364656441:/usr/src/app# bumbler
[########################################################################################################                                                                        ]
( 78/132) aws-sdk-s3...                                                                                                                                           thin (  66.78ms)
Slow requires:
    104.80  elasticsearch-dsl
    107.16  paperclip
    121.61  typhoeus
    121.98  stripe
```

Is this a known issue? How could I debug this?

**Comment by grosser** [comment]
`bundle open bumbler` and add a few puts to see where it stops

**Comment by 23tux** [comment]
@grosser I put some puts in `#require_started` and `#require_finished` and it seems like it finishes for example loading the aws gem, and then stops. When I remove the aws gem, it finishes loading the `pry-byebug` and then stops. When I remove pry-byebug it finishes loading `parallel_tests` and then stops. And so on...

So it doesn't seem to me that the problem lies within a particular gem. Any ideas on how I could debug this?

This is where I added the puts:

```
      def require_started(path)
        gem_name = self.gem_for_require(path)
        return unless gem_name

        Bumbler::Progress.item_started(:bundler, gem_name)
        puts "-> START #{gem_name}"
      end

      def require_finished(path, load_time)
        self.read_bundler_environment if @gem_state.nil?

        # Tick it off for the gem.
        gem_name = self.gem_for_require(path)
        return unless gem_name

        @gem_state[gem_name][path] = true

        if @gem_state[gem_name].values.all?
          Bumbler::Progress.item_finished(:bundler, gem_name, load_time)
        end
        puts "-> FINISH #{gem_name}"
      end
```

**Comment by joevandyk** [comment]
Running into the same problem, only gets through about 9 of the 128 gems.

**Comment by joevandyk** [comment]
![image](https://user-images.githubusercontent.com/1179/67306068-38bce800-f4ab-11e9-809d-b6c9abe7ddc1.png)

loads 100 of 128 gems

Using the Gemfile/app at https://github.com/joevandyk/bumbler-problem-repro

**Comment by 23tux** [comment]
@joevandyk interesting, we have some gems in common:

* graphql
* rails
* aws-sdk-s3
* httparty
* airbrake
* devise
* ransack
* sassc

maybe this gives us a hint whats going on

**Comment by c2ofh** [comment]
You're lucky.... I'm waiting a while for.... nothing.
![image](https://user-images.githubusercontent.com/10913793/67524316-cae20d80-f6b0-11e9-87b3-ea36872237d4.png)

**Comment by grosser** [comment]
afaik it looks like it's not finishing because the progress is `required-gems/available-gems` ... since not all available gems get required it looks like it finishes early

**Comment by grosser** [comment]
git@github.com:joevandyk/bumbler-problem-repro.git gives me 100/127 ... 

indirect dependencies do not count into the 127 hmm ...
the `@require_map` only has 122 items, so 5 gems could not be resolved
and if I track found vs known gems then these could not be found:

```
sinatra
bootsnap
byebug
newrelic_route_check
rspec-rails
rubocop
rubocop-rails
better_errors
binding_of_caller
letter_opener
mocha
simplecov
stripe-ruby-mock
vcr
webmock
activesupport
awesome_print
memoist
optimist
scripto
graphiql-rails
```

**Comment by grosser** [comment]
and webmock for example is never required ... if I add it by hand then we get 101 🤷‍♂ 

... so afaik no mystery here, if you know how to make the progress bar/UI better please reopen

**Comment by grosser** [comment]
as a general FYI you should not be loading that many gems ... do not use `Bundler.require` but load what you need manually ... check out http://github.com/zendesk/samson which scores `19/105` ;)

**Comment by 23tux** [comment]
only problem I have after refactoring some gems is, that I only get one result

```
Slow requires:
    119.14  httparty
```

and that's it. IMHO there is still something wrong here

**Comment by grosser** [comment]
try with the master version and `--all`, or us `-t 1`, that should show all
load times ... I'm still fixing 1 bug where it did not count path
correctly, but that's just an edge-case
