### ISSUE TITLE
not working in rails 6.0

### ISSUE THREAD

**Issue by sobakasu** [nevir/Bumbler#24]
```
         3: from /home/andrew/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/deprecation/proxy_wrappers.rb:128:in `new'
         2: from /home/andrew/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/deprecation/proxy_wrappers.rb:128:in `new'
         1: from /home/andrew/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/deprecation/proxy_wrappers.rb:132:in `initialize'
/home/andrew/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/deprecation/proxy_wrappers.rb:168:in `method_missing': private method `warn' called for nil:NilClass (NoMethodError)
```

**Comment by grosser** [comment]
sounds like the logger is not initialized yet ... is there more backtrace, looks like it's just inside rails ?
try disabling rails backtrace cleaner, it might be hiding gem backtraces

**Comment by sobakasu** [comment]
full backtrace attached. this is for a newly created rails 6 apps.
[bumbler.txt](https://github.com/nevir/Bumbler/files/3612384/bumbler.txt)

**Comment by grosser** [comment]
so  error  is from https://github.com/nevir/Bumbler/blob/v0.5.0/lib/bumbler/hooks.rb#L35

... most likely hitting some deprecation, open up /home/andrew/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/deprecation/proxy_wrappers.rb:168 and add a `puts` for whatever it  tries to send as warning ... that should show what's going wrong

**Comment by Laykou** [comment]
👍

**Comment by Laykou** [comment]
@nevir Do you think you could help here, please?

**Comment by grosser** [comment]
make an example rails 6 app where it does not work and I can take a look ... `gem open bumbler` and a bit of puts should go a long way :)

**Comment by cw2908** [comment]
I also have this problem. When I get a chance I will try to create a stand alone rails app similar to the one I'm working on. 


[stacktrace](https://gist.github.com/cw2908/8bfa74fe2bd92ead99448d7e7967b7d7) (fails checking rspec-rails but also others if I remove this gem)

When I log the values where it fails:
```
RAILS::VERSION::String: '6.0.1'
@deprecator: nil
called: :require
args: ["active_support/inflector/methods"]
block: nil
```

The rspec-rails line in question from the stacktrace is `require 'rails/source_annotation_extractor'` From rails console I can resolve `SourceAnnotationExtractor` or `Rails::SourceAnnotationExtractor`. 


In my appplication.rb I have:

```
  logger = ActiveSupport::Logger.new(STDOUT)
  logger.formatter = config.log_formatter
  config.log_tags = [ :uuid ]
  config.logger = ActiveSupport::TaggedLogging.new(logger)
```
But it also fails I remove this. 

Any idea?

**Comment by gbxl** [comment]
Same issue with Rails 6.0.1

**Comment by grosser** [comment]
I got this when not adding bumbler to the gemfile:
```
bumbler-0.6.0/lib/bumbler/hooks.rb:32:in `require': cannot load such file -- bumbler/stats (LoadError)
```

then with `bundle add administrate`

```
NoMethodError: private method `warn' called for nil:NilClass
vendor/bundle/gems/activesupport-6.0.2.2/lib/active_support/deprecation/proxy_wrappers.rb:168:in `method_missing'
vendor/bundle/gems/activesupport-6.0.2.2/lib/active_support/deprecation/proxy_wrappers.rb:132:in `initialize'
vendor/bundle/gems/activesupport-6.0.2.2/lib/active_support/deprecation/proxy_wrappers.rb:128:in `new'
vendor/bundle/gems/activesupport-6.0.2.2/lib/active_support/deprecation/proxy_wrappers.rb:128:in `new'
vendor/bundle/gems/railties-6.0.2.2/lib/rails/source_annotation_extractor.rb:162:in `<top (required)>'
vendor/bundle/gems/bumbler-0.6.0/lib/bumbler/hooks.rb:32:in `require'
```

... failure comes from

```
ActiveSupport::Deprecation::DeprecatedConstantProxy.
  new("SourceAnnotationExtractor", "Rails::SourceAnnotationExtractor")
```

which triggers a require for `activesupport/deprecations` but from itself ....
... which then goes into `          @deprecator.warn(@message, caller_locations)`

... removing the line that uses `ActiveSupport::Deprecation::DeprecatedConstantProxy` works
... not sure why administrate triggers it ...
but rewriting it fixes the issue, so let's do that :)
https://github.com/nevir/Bumbler/pull/26

**Comment by grosser** [comment]
0.7.0
